/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as NutzungsbedingungenRouteImport } from './routes/nutzungsbedingungen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OnboardingHelperRouteImport } from './routes/onboarding.helper'
import { Route as OnboardingFamilyRouteImport } from './routes/onboarding.family'
import { Route as HelperProfileRouteImport } from './routes/helper.profile'
import { Route as HelperPayoutsRouteImport } from './routes/helper.payouts'
import { Route as HelperJobsRouteImport } from './routes/helper.jobs'
import { Route as HelperDashboardRouteImport } from './routes/helper.dashboard'
import { Route as HelperAvailabilityRouteImport } from './routes/helper.availability'
import { Route as HelperAppointmentsRouteImport } from './routes/helper.appointments'
import { Route as FamilyRequestsRouteImport } from './routes/family.requests'
import { Route as FamilyProfileRouteImport } from './routes/family.profile'
import { Route as FamilyInvoicesRouteImport } from './routes/family.invoices'
import { Route as FamilyFavoritesRouteImport } from './routes/family.favorites'
import { Route as FamilyDiscoverRouteImport } from './routes/family.discover'
import { Route as FamilyDashboardRouteImport } from './routes/family.dashboard'
import { Route as FamilyBookingsRouteImport } from './routes/family.bookings'
import { Route as FamilyBookingRouteImport } from './routes/family.booking'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminHelpersRouteImport } from './routes/admin.helpers'
import { Route as HelperMessagesIndexRouteImport } from './routes/helper.messages.index'
import { Route as HelperJobsIndexRouteImport } from './routes/helper.jobs.index'
import { Route as FamilyMessagesIndexRouteImport } from './routes/family.messages.index'
import { Route as HelperMessagesIdRouteImport } from './routes/helper.messages.$id'
import { Route as HelperJobsIdRouteImport } from './routes/helper.jobs.$id'
import { Route as HelperAppointmentsIdRouteImport } from './routes/helper.appointments.$id'
import { Route as HelperIdCvRouteImport } from './routes/helper.$id.cv'
import { Route as FamilyMessagesIdRouteImport } from './routes/family.messages.$id'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const NutzungsbedingungenRoute = NutzungsbedingungenRouteImport.update({
  id: '/nutzungsbedingungen',
  path: '/nutzungsbedingungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingHelperRoute = OnboardingHelperRouteImport.update({
  id: '/onboarding/helper',
  path: '/onboarding/helper',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFamilyRoute = OnboardingFamilyRouteImport.update({
  id: '/onboarding/family',
  path: '/onboarding/family',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperProfileRoute = HelperProfileRouteImport.update({
  id: '/helper/profile',
  path: '/helper/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperPayoutsRoute = HelperPayoutsRouteImport.update({
  id: '/helper/payouts',
  path: '/helper/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperJobsRoute = HelperJobsRouteImport.update({
  id: '/helper/jobs',
  path: '/helper/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperDashboardRoute = HelperDashboardRouteImport.update({
  id: '/helper/dashboard',
  path: '/helper/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperAvailabilityRoute = HelperAvailabilityRouteImport.update({
  id: '/helper/availability',
  path: '/helper/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperAppointmentsRoute = HelperAppointmentsRouteImport.update({
  id: '/helper/appointments',
  path: '/helper/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRequestsRoute = FamilyRequestsRouteImport.update({
  id: '/family/requests',
  path: '/family/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyProfileRoute = FamilyProfileRouteImport.update({
  id: '/family/profile',
  path: '/family/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyInvoicesRoute = FamilyInvoicesRouteImport.update({
  id: '/family/invoices',
  path: '/family/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyFavoritesRoute = FamilyFavoritesRouteImport.update({
  id: '/family/favorites',
  path: '/family/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyDiscoverRoute = FamilyDiscoverRouteImport.update({
  id: '/family/discover',
  path: '/family/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyDashboardRoute = FamilyDashboardRouteImport.update({
  id: '/family/dashboard',
  path: '/family/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyBookingsRoute = FamilyBookingsRouteImport.update({
  id: '/family/bookings',
  path: '/family/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyBookingRoute = FamilyBookingRouteImport.update({
  id: '/family/booking',
  path: '/family/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHelpersRoute = AdminHelpersRouteImport.update({
  id: '/admin/helpers',
  path: '/admin/helpers',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperMessagesIndexRoute = HelperMessagesIndexRouteImport.update({
  id: '/helper/messages/',
  path: '/helper/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperJobsIndexRoute = HelperJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelperJobsRoute,
} as any)
const FamilyMessagesIndexRoute = FamilyMessagesIndexRouteImport.update({
  id: '/family/messages/',
  path: '/family/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperMessagesIdRoute = HelperMessagesIdRouteImport.update({
  id: '/helper/messages/$id',
  path: '/helper/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HelperJobsIdRoute = HelperJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HelperJobsRoute,
} as any)
const HelperAppointmentsIdRoute = HelperAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HelperAppointmentsRoute,
} as any)
const HelperIdCvRoute = HelperIdCvRouteImport.update({
  id: '/helper/$id/cv',
  path: '/helper/$id/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyMessagesIdRoute = FamilyMessagesIdRouteImport.update({
  id: '/family/messages/$id',
  path: '/family/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/nutzungsbedingungen': typeof NutzungsbedingungenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/family/booking': typeof FamilyBookingRoute
  '/family/bookings': typeof FamilyBookingsRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/discover': typeof FamilyDiscoverRoute
  '/family/favorites': typeof FamilyFavoritesRoute
  '/family/invoices': typeof FamilyInvoicesRoute
  '/family/profile': typeof FamilyProfileRoute
  '/family/requests': typeof FamilyRequestsRoute
  '/helper/appointments': typeof HelperAppointmentsRouteWithChildren
  '/helper/availability': typeof HelperAvailabilityRoute
  '/helper/dashboard': typeof HelperDashboardRoute
  '/helper/jobs': typeof HelperJobsRouteWithChildren
  '/helper/payouts': typeof HelperPayoutsRoute
  '/helper/profile': typeof HelperProfileRoute
  '/onboarding/family': typeof OnboardingFamilyRoute
  '/onboarding/helper': typeof OnboardingHelperRoute
  '/admin/': typeof AdminIndexRoute
  '/family/messages/$id': typeof FamilyMessagesIdRoute
  '/helper/$id/cv': typeof HelperIdCvRoute
  '/helper/appointments/$id': typeof HelperAppointmentsIdRoute
  '/helper/jobs/$id': typeof HelperJobsIdRoute
  '/helper/messages/$id': typeof HelperMessagesIdRoute
  '/family/messages/': typeof FamilyMessagesIndexRoute
  '/helper/jobs/': typeof HelperJobsIndexRoute
  '/helper/messages/': typeof HelperMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/nutzungsbedingungen': typeof NutzungsbedingungenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/family/booking': typeof FamilyBookingRoute
  '/family/bookings': typeof FamilyBookingsRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/discover': typeof FamilyDiscoverRoute
  '/family/favorites': typeof FamilyFavoritesRoute
  '/family/invoices': typeof FamilyInvoicesRoute
  '/family/profile': typeof FamilyProfileRoute
  '/family/requests': typeof FamilyRequestsRoute
  '/helper/appointments': typeof HelperAppointmentsRouteWithChildren
  '/helper/availability': typeof HelperAvailabilityRoute
  '/helper/dashboard': typeof HelperDashboardRoute
  '/helper/payouts': typeof HelperPayoutsRoute
  '/helper/profile': typeof HelperProfileRoute
  '/onboarding/family': typeof OnboardingFamilyRoute
  '/onboarding/helper': typeof OnboardingHelperRoute
  '/admin': typeof AdminIndexRoute
  '/family/messages/$id': typeof FamilyMessagesIdRoute
  '/helper/$id/cv': typeof HelperIdCvRoute
  '/helper/appointments/$id': typeof HelperAppointmentsIdRoute
  '/helper/jobs/$id': typeof HelperJobsIdRoute
  '/helper/messages/$id': typeof HelperMessagesIdRoute
  '/family/messages': typeof FamilyMessagesIndexRoute
  '/helper/jobs': typeof HelperJobsIndexRoute
  '/helper/messages': typeof HelperMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/nutzungsbedingungen': typeof NutzungsbedingungenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/admin/helpers': typeof AdminHelpersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/family/booking': typeof FamilyBookingRoute
  '/family/bookings': typeof FamilyBookingsRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/discover': typeof FamilyDiscoverRoute
  '/family/favorites': typeof FamilyFavoritesRoute
  '/family/invoices': typeof FamilyInvoicesRoute
  '/family/profile': typeof FamilyProfileRoute
  '/family/requests': typeof FamilyRequestsRoute
  '/helper/appointments': typeof HelperAppointmentsRouteWithChildren
  '/helper/availability': typeof HelperAvailabilityRoute
  '/helper/dashboard': typeof HelperDashboardRoute
  '/helper/jobs': typeof HelperJobsRouteWithChildren
  '/helper/payouts': typeof HelperPayoutsRoute
  '/helper/profile': typeof HelperProfileRoute
  '/onboarding/family': typeof OnboardingFamilyRoute
  '/onboarding/helper': typeof OnboardingHelperRoute
  '/admin/': typeof AdminIndexRoute
  '/family/messages/$id': typeof FamilyMessagesIdRoute
  '/helper/$id/cv': typeof HelperIdCvRoute
  '/helper/appointments/$id': typeof HelperAppointmentsIdRoute
  '/helper/jobs/$id': typeof HelperJobsIdRoute
  '/helper/messages/$id': typeof HelperMessagesIdRoute
  '/family/messages/': typeof FamilyMessagesIndexRoute
  '/helper/jobs/': typeof HelperJobsIndexRoute
  '/helper/messages/': typeof HelperMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/nutzungsbedingungen'
    | '/ueber-uns'
    | '/admin/helpers'
    | '/admin/payments'
    | '/admin/verification'
    | '/family/booking'
    | '/family/bookings'
    | '/family/dashboard'
    | '/family/discover'
    | '/family/favorites'
    | '/family/invoices'
    | '/family/profile'
    | '/family/requests'
    | '/helper/appointments'
    | '/helper/availability'
    | '/helper/dashboard'
    | '/helper/jobs'
    | '/helper/payouts'
    | '/helper/profile'
    | '/onboarding/family'
    | '/onboarding/helper'
    | '/admin/'
    | '/family/messages/$id'
    | '/helper/$id/cv'
    | '/helper/appointments/$id'
    | '/helper/jobs/$id'
    | '/helper/messages/$id'
    | '/family/messages/'
    | '/helper/jobs/'
    | '/helper/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/nutzungsbedingungen'
    | '/ueber-uns'
    | '/admin/helpers'
    | '/admin/payments'
    | '/admin/verification'
    | '/family/booking'
    | '/family/bookings'
    | '/family/dashboard'
    | '/family/discover'
    | '/family/favorites'
    | '/family/invoices'
    | '/family/profile'
    | '/family/requests'
    | '/helper/appointments'
    | '/helper/availability'
    | '/helper/dashboard'
    | '/helper/payouts'
    | '/helper/profile'
    | '/onboarding/family'
    | '/onboarding/helper'
    | '/admin'
    | '/family/messages/$id'
    | '/helper/$id/cv'
    | '/helper/appointments/$id'
    | '/helper/jobs/$id'
    | '/helper/messages/$id'
    | '/family/messages'
    | '/helper/jobs'
    | '/helper/messages'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/nutzungsbedingungen'
    | '/ueber-uns'
    | '/admin/helpers'
    | '/admin/payments'
    | '/admin/verification'
    | '/family/booking'
    | '/family/bookings'
    | '/family/dashboard'
    | '/family/discover'
    | '/family/favorites'
    | '/family/invoices'
    | '/family/profile'
    | '/family/requests'
    | '/helper/appointments'
    | '/helper/availability'
    | '/helper/dashboard'
    | '/helper/jobs'
    | '/helper/payouts'
    | '/helper/profile'
    | '/onboarding/family'
    | '/onboarding/helper'
    | '/admin/'
    | '/family/messages/$id'
    | '/helper/$id/cv'
    | '/helper/appointments/$id'
    | '/helper/jobs/$id'
    | '/helper/messages/$id'
    | '/family/messages/'
    | '/helper/jobs/'
    | '/helper/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  NutzungsbedingungenRoute: typeof NutzungsbedingungenRoute
  UeberUnsRoute: typeof UeberUnsRoute
  AdminHelpersRoute: typeof AdminHelpersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  FamilyBookingRoute: typeof FamilyBookingRoute
  FamilyBookingsRoute: typeof FamilyBookingsRoute
  FamilyDashboardRoute: typeof FamilyDashboardRoute
  FamilyDiscoverRoute: typeof FamilyDiscoverRoute
  FamilyFavoritesRoute: typeof FamilyFavoritesRoute
  FamilyInvoicesRoute: typeof FamilyInvoicesRoute
  FamilyProfileRoute: typeof FamilyProfileRoute
  FamilyRequestsRoute: typeof FamilyRequestsRoute
  HelperAppointmentsRoute: typeof HelperAppointmentsRouteWithChildren
  HelperAvailabilityRoute: typeof HelperAvailabilityRoute
  HelperDashboardRoute: typeof HelperDashboardRoute
  HelperJobsRoute: typeof HelperJobsRouteWithChildren
  HelperPayoutsRoute: typeof HelperPayoutsRoute
  HelperProfileRoute: typeof HelperProfileRoute
  OnboardingFamilyRoute: typeof OnboardingFamilyRoute
  OnboardingHelperRoute: typeof OnboardingHelperRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FamilyMessagesIdRoute: typeof FamilyMessagesIdRoute
  HelperIdCvRoute: typeof HelperIdCvRoute
  HelperMessagesIdRoute: typeof HelperMessagesIdRoute
  FamilyMessagesIndexRoute: typeof FamilyMessagesIndexRoute
  HelperMessagesIndexRoute: typeof HelperMessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutzungsbedingungen': {
      id: '/nutzungsbedingungen'
      path: '/nutzungsbedingungen'
      fullPath: '/nutzungsbedingungen'
      preLoaderRoute: typeof NutzungsbedingungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/helper': {
      id: '/onboarding/helper'
      path: '/onboarding/helper'
      fullPath: '/onboarding/helper'
      preLoaderRoute: typeof OnboardingHelperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/family': {
      id: '/onboarding/family'
      path: '/onboarding/family'
      fullPath: '/onboarding/family'
      preLoaderRoute: typeof OnboardingFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper/profile': {
      id: '/helper/profile'
      path: '/helper/profile'
      fullPath: '/helper/profile'
      preLoaderRoute: typeof HelperProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper/payouts': {
      id: '/helper/payouts'
      path: '/helper/payouts'
      fullPath: '/helper/payouts'
      preLoaderRoute: typeof HelperPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper/jobs': {
      id: '/helper/jobs'
      path: '/helper/jobs'
      fullPath: '/helper/jobs'
      preLoaderRoute: typeof HelperJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper/dashboard': {
      id: '/helper/dashboard'
      path: '/helper/dashboard'
      fullPath: '/helper/dashboard'
      preLoaderRoute: typeof HelperDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper/availability': {
      id: '/helper/availability'
      path: '/helper/availability'
      fullPath: '/helper/availability'
      preLoaderRoute: typeof HelperAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper/appointments': {
      id: '/helper/appointments'
      path: '/helper/appointments'
      fullPath: '/helper/appointments'
      preLoaderRoute: typeof HelperAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/requests': {
      id: '/family/requests'
      path: '/family/requests'
      fullPath: '/family/requests'
      preLoaderRoute: typeof FamilyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/profile': {
      id: '/family/profile'
      path: '/family/profile'
      fullPath: '/family/profile'
      preLoaderRoute: typeof FamilyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/invoices': {
      id: '/family/invoices'
      path: '/family/invoices'
      fullPath: '/family/invoices'
      preLoaderRoute: typeof FamilyInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/favorites': {
      id: '/family/favorites'
      path: '/family/favorites'
      fullPath: '/family/favorites'
      preLoaderRoute: typeof FamilyFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/discover': {
      id: '/family/discover'
      path: '/family/discover'
      fullPath: '/family/discover'
      preLoaderRoute: typeof FamilyDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/dashboard': {
      id: '/family/dashboard'
      path: '/family/dashboard'
      fullPath: '/family/dashboard'
      preLoaderRoute: typeof FamilyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/bookings': {
      id: '/family/bookings'
      path: '/family/bookings'
      fullPath: '/family/bookings'
      preLoaderRoute: typeof FamilyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/booking': {
      id: '/family/booking'
      path: '/family/booking'
      fullPath: '/family/booking'
      preLoaderRoute: typeof FamilyBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/helpers': {
      id: '/admin/helpers'
      path: '/admin/helpers'
      fullPath: '/admin/helpers'
      preLoaderRoute: typeof AdminHelpersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper/messages/': {
      id: '/helper/messages/'
      path: '/helper/messages'
      fullPath: '/helper/messages/'
      preLoaderRoute: typeof HelperMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper/jobs/': {
      id: '/helper/jobs/'
      path: '/'
      fullPath: '/helper/jobs/'
      preLoaderRoute: typeof HelperJobsIndexRouteImport
      parentRoute: typeof HelperJobsRoute
    }
    '/family/messages/': {
      id: '/family/messages/'
      path: '/family/messages'
      fullPath: '/family/messages/'
      preLoaderRoute: typeof FamilyMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper/messages/$id': {
      id: '/helper/messages/$id'
      path: '/helper/messages/$id'
      fullPath: '/helper/messages/$id'
      preLoaderRoute: typeof HelperMessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helper/jobs/$id': {
      id: '/helper/jobs/$id'
      path: '/$id'
      fullPath: '/helper/jobs/$id'
      preLoaderRoute: typeof HelperJobsIdRouteImport
      parentRoute: typeof HelperJobsRoute
    }
    '/helper/appointments/$id': {
      id: '/helper/appointments/$id'
      path: '/$id'
      fullPath: '/helper/appointments/$id'
      preLoaderRoute: typeof HelperAppointmentsIdRouteImport
      parentRoute: typeof HelperAppointmentsRoute
    }
    '/helper/$id/cv': {
      id: '/helper/$id/cv'
      path: '/helper/$id/cv'
      fullPath: '/helper/$id/cv'
      preLoaderRoute: typeof HelperIdCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/messages/$id': {
      id: '/family/messages/$id'
      path: '/family/messages/$id'
      fullPath: '/family/messages/$id'
      preLoaderRoute: typeof FamilyMessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HelperAppointmentsRouteChildren {
  HelperAppointmentsIdRoute: typeof HelperAppointmentsIdRoute
}

const HelperAppointmentsRouteChildren: HelperAppointmentsRouteChildren = {
  HelperAppointmentsIdRoute: HelperAppointmentsIdRoute,
}

const HelperAppointmentsRouteWithChildren =
  HelperAppointmentsRoute._addFileChildren(HelperAppointmentsRouteChildren)

interface HelperJobsRouteChildren {
  HelperJobsIdRoute: typeof HelperJobsIdRoute
  HelperJobsIndexRoute: typeof HelperJobsIndexRoute
}

const HelperJobsRouteChildren: HelperJobsRouteChildren = {
  HelperJobsIdRoute: HelperJobsIdRoute,
  HelperJobsIndexRoute: HelperJobsIndexRoute,
}

const HelperJobsRouteWithChildren = HelperJobsRoute._addFileChildren(
  HelperJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  NutzungsbedingungenRoute: NutzungsbedingungenRoute,
  UeberUnsRoute: UeberUnsRoute,
  AdminHelpersRoute: AdminHelpersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  FamilyBookingRoute: FamilyBookingRoute,
  FamilyBookingsRoute: FamilyBookingsRoute,
  FamilyDashboardRoute: FamilyDashboardRoute,
  FamilyDiscoverRoute: FamilyDiscoverRoute,
  FamilyFavoritesRoute: FamilyFavoritesRoute,
  FamilyInvoicesRoute: FamilyInvoicesRoute,
  FamilyProfileRoute: FamilyProfileRoute,
  FamilyRequestsRoute: FamilyRequestsRoute,
  HelperAppointmentsRoute: HelperAppointmentsRouteWithChildren,
  HelperAvailabilityRoute: HelperAvailabilityRoute,
  HelperDashboardRoute: HelperDashboardRoute,
  HelperJobsRoute: HelperJobsRouteWithChildren,
  HelperPayoutsRoute: HelperPayoutsRoute,
  HelperProfileRoute: HelperProfileRoute,
  OnboardingFamilyRoute: OnboardingFamilyRoute,
  OnboardingHelperRoute: OnboardingHelperRoute,
  AdminIndexRoute: AdminIndexRoute,
  FamilyMessagesIdRoute: FamilyMessagesIdRoute,
  HelperIdCvRoute: HelperIdCvRoute,
  HelperMessagesIdRoute: HelperMessagesIdRoute,
  FamilyMessagesIndexRoute: FamilyMessagesIndexRoute,
  HelperMessagesIndexRoute: HelperMessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
